<a href="https://colab.research.google.com/github/DaffaYenza/CodeProject3/blob/main/Tugas_Session_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report , confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_names = ["Sample code number", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape",
                "Marginal Adhesion", "Single Epithelial Cell Size", "Bare Nuclei", "Bland Chromatin",
                "Normal Nucleoli", "Mitoses", "Class"]
df = pd.read_csv(url, names=column_names)

df.replace('?', pd.NA, inplace=True)
df.dropna(inplace=True)

df.head(50)

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
5,1017122,8,10,10,8,7,10,9,7,1,4
6,1018099,1,1,1,1,2,10,3,1,1,2
7,1018561,2,1,2,1,2,1,3,1,1,2
8,1033078,2,1,1,1,2,1,1,1,5,2
9,1033078,4,2,1,1,2,1,2,1,1,2
10,1035283,1,1,1,1,1,1,3,1,1,2
11,1036172,2,1,1,1,2,1,2,1,1,2
12,1041801,5,3,3,3,2,3,4,4,1,4
13,1043999,1,1,1,1,2,3,3,1,1,2
14,1044572,8,7,5,10,7,9,5,5,4,4
15,1047630,7,4,6,4,6,1,4,3,1,4
16,1048672,4,1,1,1,2,1,2,1,1,2
17,1049815,4,1,1,1,2,1,3,1,1,2
18,1050670,10,7,7,6,4,10,4,1,2,4
19,1050718,6,1,1,1,2,1,3,1,1,2
20,1054590,7,3,2,10,5,10,5,4,4,4
21,1054593,10,5,5,3,6,7,7,10,1,4
22,1056784,3,1,1,1,2,1,2,1,1,2
24,1059552,1,1,1,1,2,1,3,1,1,2
25,1065726,5,2,3,4,2,7,3,6,1,4
26,1066373,3,2,1,1,1,1,2,1,1,2
27,1066979,5,1,1,1,2,1,2,1,1,2
28,1067444,2,1,1,1,2,1,2,1,1,2
29,1070935,1,1,3,1,2,1,1,1,1,2
30,1070935,3,1,1,1,1,1,2,1,1,2
31,1071760,2,1,1,1,2,1,3,1,1,2
32,1072179,10,7,7,3,8,5,7,4,3,4
33,1074610,2,1,1,2,2,1,3,1,1,2
34,1075123,3,1,2,1,2,1,2,1,1,2
35,1079304,2,1,1,1,2,1,2,1,1,2
36,1080185,10,10,10,8,6,1,8,9,1,4
37,1081791,6,2,1,1,1,1,7,1,1,2
38,1084584,5,4,4,9,2,10,5,6,1,4
39,1091262,2,5,3,3,6,7,7,5,1,4
41,1099510,10,4,3,1,3,3,6,5,2,4
42,1100524,6,10,10,2,8,10,7,3,3,4
43,1102573,5,6,5,6,10,1,3,1,1,4
44,1103608,10,10,10,4,8,1,8,10,1,4
45,1103722,1,1,1,1,2,1,2,1,2,2
46,1105257,3,7,7,4,4,9,4,8,1,4
47,1105524,1,1,1,1,2,1,2,1,1,2
48,1106095,4,1,1,3,2,1,3,1,1,2
49,1106829,7,8,7,2,4,8,3,8,2,4
50,1108370,9,5,8,1,2,3,2,1,5,4
51,1108449,5,3,3,4,2,4,3,4,1,4

In [ ]:
df.shape

(683, 11)

In [ ]:
df['Class'] = df['Class'].apply(lambda x : 1 if x == 4 else 0)
df

,Sample code number,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,0
1,1002945,5,4,4,5,7,10,3,2,1,0
2,1015425,3,1,1,1,2,2,3,1,1,0
3,1016277,6,8,8,1,3,4,3,7,1,0
4,1017023,4,1,1,3,2,1,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,0
695,841769,2,1,1,1,2,1,1,1,1,0
696,888820,5,10,10,3,7,3,8,10,2,1
697,897471,4,8,6,4,3,4,10,6,1,1
698,897471,4,8,8,5,4,5,10,4,1,1

In [ ]:
# Check missing values
df.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [ ]:
X = df.iloc[:,0:10]
y = df.iloc[:,10]

In [ ]:
# Splitting data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=11)

In [ ]:
# Scalling
s = StandardScaler()
print
X_train = s.fit_transform(X_train)
X_test = s.fit_transform(X_test)

# **MODELING**

In [ ]:
# KKN
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [ ]:
y_predknn = knn.predict(X_test)

In [ ]:
print('Accuracy score KNN: ', knn.score(X_test, y_test))

Accuracy score KNN:  0.9854014598540146

In [ ]:
print(classification_report(y_test, y_predknn))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99        86
           1       0.98      0.98      0.98        51

    accuracy                           0.99       137
   macro avg       0.98      0.98      0.98       137
weighted avg       0.99      0.99      0.99       137

In [ ]:
cm = confusion_matrix(y_test, y_predknn)
print(cm)

[[85  1]
 [ 1 50]]

In [ ]:
# RandomForest
ran = RandomForestClassifier(n_estimators = 300 , random_state=100)
ran.fit(X_train ,y_train)

RandomForestClassifier(n_estimators=300, random_state=100)

In [ ]:
print(f'train score of RandomForestClassifier : {ran.score(X_train , y_train)}')
print(f'test score of RandomForestClassifier : {ran.score(X_test , y_test)}')

train score of RandomForestClassifier : 1.0
test score of RandomForestClassifier : 0.9927007299270073

In [ ]:
y_predran = ran.predict(X_test)

In [ ]:
print('Accuracy score random forest:', ran.score(X_test, y_test))

Accuracy score random forest: 0.9927007299270073

In [ ]:
cm = confusion_matrix(y_test, y_predran)
print(cm)

[[85  1]
 [ 0 51]]

In [ ]:
print(classification_report(y_test, y_predran))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        86
           1       0.98      1.00      0.99        51

    accuracy                           0.99       137
   macro avg       0.99      0.99      0.99       137
weighted avg       0.99      0.99      0.99       137